name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SHA6: ${gihub.sha::6}
    
    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: wordpress
        region: us-west-1
        tags: ${{ steps.slug.outputs.sha8 }}
        create_repo: true
        image_scanning_configuration: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json
